language: cpp
before_script:
- sudo apt-get install libgtest-dev -y
script:
- mkdir gtest
- cd gtest
- cmake /usr/src/gtest/
- cmake --build .
- cd ..
- cmake .
- cmake --build .
- ctest .
- cmake --build . --target package
deploy:
  provider: bintray
  file: description.json
  user: $BINTRAY_USER
  key: $BINTRAY_API_KEY
  skip_cleanup: true
